spring:
  datasource:
    url: jdbc:mysql://3.38.151.77:3306/meetpick  # MySQL URL (데이터베이스 이름 포함)
    username: root                             # MySQL 사용자명
    password: abcd1234                     # MySQL 비밀번호
    driver-class-name: com.mysql.cj.jdbc.Driver  # MySQL 드라이버 클래스
    hikari:
      maximum-pool-size: 10                    # 커넥션 풀 크기
      minimum-idle: 5                           # 최소 유휴 커넥션 수
  jpa:
    hibernate:
      ddl-auto: update                         # Hibernate DDL 자동 생성 (옵션: none, update, create, create-drop)
    show-sql: true                              # SQL 로그 출력 여부
    database-platform: org.hibernate.dialect.MySQLDialect  # MySQL Dialect 설정
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 014f4cb37c727f56794afaf696a6b8d3
            client-secret: q9krpFKTlBAJ63D5iMpeN3Pdqzz1eb8x
            authorization-grant-type: authorization_code
            redirect-uri: http://35.172.251.131:8080/login/oauth2/code/kakao
            scope: profile_nickname
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
  jwt:
    secret: MBmyRKy5ewzjVqQ5mDiXkeK4ECmByFUax6I0iWgiFzs=

front:
  redirect-url: "https://meetpick.click"

logging:
  level:
    root: warn