spring:
  port: 8080  # 기본값이 8080인지 확인

  datasource:
    url: jdbc:mysql://localhost:3306/meetpick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yoo54485788@

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5595f2a84cb895af59630179b5f6d796
            client-secret: jKeP5ML0PhLvaadugrqB1gQkLpVLxRU9
            authorization-grant-type: authorization_code
#            redirect-uri: http://3.38.151.77:8080/login/oauth2/code/kakao
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
#            redirect-uri: "{baseUrl}/oauth2/authorization/kakao"
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # ✅ 변경
#            redirect-uri: http://3.38.151.77:8080/login/oauth2/code/kakao  # ✅ 변경
#            redirect-uri: "http://3.38.151.77:8080/login/oauth2/code/kakao"
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao" # ✅ 변경
#            redirect-uri: "http://3.38.151.77:8080/login/oauth2/code/kakao"
#            redirect-uri: "{baseUrl}/login/oauth2/code/kakao"
            scope: profile_nickname, profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  logging:
    file:
       name: logs/application.log  # 로그 파일 저장 경로
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor: trace
      org.springframework.security: DEBUG
      org.springframework.web: DEBUG
  jwt:
    secret: MBmyRKy5ewzjVqQ5mDiXkeK4ECmByFUax6I0iWgiFzs=

  session:
    store-type: none  # ✅ Redis 사용하지 않음 (테스트용)
  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      mappings:
        enabled: true




