spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetpick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: yoo54485788@

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 5595f2a84cb895af59630179b5f6d796
            client-secret: jKeP5ML0PhLvaadugrqB1gQkLpVLxRU9
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080/login/oauth2/code/kakao
            scope: profile_nickname, profile_image
            client-name: Kakao
            client-authentication-method: client_secret_post
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id

  logging:
    level:
      org.hibernate.SQL: debug
      org.hibernate.type.descriptor: trace
      org.springframework.security: DEBUG
  jwt:
    secret: MBmyRKy5ewzjVqQ5mDiXkeK4ECmByFUax6I0iWgiFzs=

