spring:
  datasource:
    url: jdbc:mysql://localhost:3306/meetpick?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root # MySQL 사용자 이름
    password: yoo54485788@ # MySQL 비밀번호
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true           # SQL 쿼리 로깅 활성화
    properties:
      hibernate.format_sql: true # SQL 포맷팅 활성화
  h2: # H2 설정 제거
    console:
      enabled: false
logging:
  level:
    org:
      hibernate:
        SQL: debug            # Hibernate SQL 로깅
        type:
          descriptor: trace   # Hibernate 매핑 관련 로깅
kakao:
  client_id: f637c459ef6d71c3f370cc02b25b9139
  redirect_uri: http://localhost:8080/callback
